---
title: "Café"
author: "Antônio Boll"
date: "4/25/2021"
output: html_document
---

## Dados

```{r cafe}
cafe <- read.csv(file="~/Desktop/cafedados1.csv",head=TRUE)
cafe2 <- read.csv(file="~/Desktop/cafedados2.csv",head=TRUE)
cafe3 <- read.csv(file="~/Desktop/cafedados3.csv",head=TRUE)
```

## Gráficos

```{r cafe2}
library(ggplot2)
library(hrbrthemes)
options("scipen"=100, "digits"=4)
Ano <- cafe$Year
Área <- cafe$Value
ggplot(mapping = aes(x=Ano, y=Área)) +
  geom_line(color="#69b3a6", size=0.5) +
  theme_replace() +
  ggtitle("Área colhida de café em relação ao tempo no Brasil", 
        "Gráfico em hectares por anos")

```

```{r cafe3}
Ano <- cafe2$Year
Área <- cafe2$Value
ggplot(mapping = aes(x=Ano, y=Área)) +
  geom_line(color="#69b3a6", size=0.5) +
  theme_replace() +
  ggtitle("Quantidade de café destinado a produtos agrícolas 
          em relação ao tempo no Brasil", 
        "Gráfico em hectares por anos")

```

```{r cafe4}
Ano <- cafe3$Year
Quantidade <- cafe3$Value
ggplot(mapping = aes(x=Ano, y=Quantidade)) +
  geom_line(color="#69b3a6", size=0.5) +
  theme_replace() +
  ggtitle("Produção de café em relação ao tempo no Brasil", 
        "Gráfico em toneladas por anos")
```